data:
  path: data/dreamt/processed_BVP_ACC_up_sample_datasets
  train_path: finetune_train_dataset_sub34.pt
  val_path: finetune_val_dataset_sub34.pt
  test_path: finetune_test_dataset_sub34.pt
  low_data_mode: False
  batch_size: 128

model:
  upstream_ckpt: checkpoints/ffm_dreamt_BVP_ACC_upsample.pt

results:
  save_path: outputs/dreamt_sleep.csv